# Generated by Django 3.2 on 2023-05-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretitle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-title',), 'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
    ]
